// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum PigeonSensorPosition: Int {
  case back = 0
  case front = 1
  case unknown = 2
}

/// Video recording quality, from [sd] to [uhd], with [highest] and [lowest] to
/// let the device choose the best/worst quality available.
/// [highest] is the default quality.
///
/// Qualities are defined like this:
/// [sd] < [hd] < [fhd] < [uhd]
enum VideoRecordingQuality: Int {
  case lowest = 0
  case sd = 1
  case hd = 2
  case fhd = 3
  case uhd = 4
  case highest = 5
}

/// If the specified [VideoRecordingQuality] is not available on the device,
/// the [VideoRecordingQuality] will fallback to [higher] or [lower] quality.
/// [higher] is the default fallback strategy.
enum QualityFallbackStrategy: Int {
  case higher = 0
  case lower = 1
}

enum CupertinoFileType: Int {
  case quickTimeMovie = 0
  case mpeg4 = 1
  case appleM4V = 2
  case type3GPP = 3
  case type3GPP2 = 4
}

enum CupertinoCodecType: Int {
  case h264 = 0
  case hevc = 1
  case hevcWithAlpha = 2
  case jpeg = 3
  case appleProRes4444 = 4
  case appleProRes422 = 5
  case appleProRes422HQ = 6
  case appleProRes422LT = 7
  case appleProRes422Proxy = 8
}

enum PigeonSensorType: Int {
  /// A built-in wide-angle camera.
  ///
  /// The wide angle sensor is the default sensor for iOS
  case wideAngle = 0
  /// A built-in camera with a shorter focal length than that of the wide-angle camera.
  case ultraWideAngle = 1
  /// A built-in camera device with a longer focal length than the wide-angle camera.
  case telephoto = 2
  /// A device that consists of two cameras, one Infrared and one YUV.
  ///
  /// iOS only
  case trueDepth = 3
  case unknown = 4
}

enum CamerAwesomePermission: Int {
  case storage = 0
  case camera = 1
  case location = 2
  case recordAudio = 3
}

enum AnalysisImageFormat: Int {
  case yuv420 = 0
  case bgra8888 = 1
  case jpeg = 2
  case nv21 = 3
  case unknown = 4
}

enum AnalysisRotation: Int {
  case rotation0deg = 0
  case rotation90deg = 1
  case rotation180deg = 2
  case rotation270deg = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreviewSize {
  var width: Double
  var height: Double



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreviewSize? {
    let width = pigeonVar_list[0] as! Double
    let height = pigeonVar_list[1] as! Double

    return PreviewSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ExifPreferences {
  var saveGPSLocation: Bool



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExifPreferences? {
    let saveGPSLocation = pigeonVar_list[0] as! Bool

    return ExifPreferences(
      saveGPSLocation: saveGPSLocation
    )
  }
  func toList() -> [Any?] {
    return [
      saveGPSLocation
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonSensor {
  var position: PigeonSensorPosition
  var type: PigeonSensorType
  var deviceId: String? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonSensor? {
    let position = pigeonVar_list[0] as! PigeonSensorPosition
    let type = pigeonVar_list[1] as! PigeonSensorType
    let deviceId: String? = nilOrValue(pigeonVar_list[2])

    return PigeonSensor(
      position: position,
      type: type,
      deviceId: deviceId
    )
  }
  func toList() -> [Any?] {
    return [
      position,
      type,
      deviceId,
    ]
  }
}

/// Video recording options. Some of them are specific to each platform.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoOptions {
  /// Enable audio while video recording
  var enableAudio: Bool
  /// The quality of the video recording, defaults to [VideoRecordingQuality.highest].
  var quality: VideoRecordingQuality? = nil
  var android: AndroidVideoOptions? = nil
  var ios: CupertinoVideoOptions? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoOptions? {
    let enableAudio = pigeonVar_list[0] as! Bool
    let quality: VideoRecordingQuality? = nilOrValue(pigeonVar_list[1])
    let android: AndroidVideoOptions? = nilOrValue(pigeonVar_list[2])
    let ios: CupertinoVideoOptions? = nilOrValue(pigeonVar_list[3])

    return VideoOptions(
      enableAudio: enableAudio,
      quality: quality,
      android: android,
      ios: ios
    )
  }
  func toList() -> [Any?] {
    return [
      enableAudio,
      quality,
      android,
      ios,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidVideoOptions {
  /// The bitrate of the video recording. Only set it if a custom bitrate is
  /// desired.
  var bitrate: Int64? = nil
  var fallbackStrategy: QualityFallbackStrategy? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidVideoOptions? {
    let bitrate: Int64? = isNullish(pigeonVar_list[0]) ? nil : (pigeonVar_list[0] is Int64? ? pigeonVar_list[0] as! Int64? : Int64(pigeonVar_list[0] as! Int32))
    let fallbackStrategy: QualityFallbackStrategy? = nilOrValue(pigeonVar_list[1])

    return AndroidVideoOptions(
      bitrate: bitrate,
      fallbackStrategy: fallbackStrategy
    )
  }
  func toList() -> [Any?] {
    return [
      bitrate,
      fallbackStrategy,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CupertinoVideoOptions {
  /// Specify video file type, defaults to [AVFileTypeQuickTimeMovie].
  var fileType: CupertinoFileType? = nil
  /// Specify video codec, defaults to [AVVideoCodecTypeH264].
  var codec: CupertinoCodecType? = nil
  /// Specify video fps, defaults to [30].
  var fps: Int64? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CupertinoVideoOptions? {
    let fileType: CupertinoFileType? = nilOrValue(pigeonVar_list[0])
    let codec: CupertinoCodecType? = nilOrValue(pigeonVar_list[1])
    let fps: Int64? = isNullish(pigeonVar_list[2]) ? nil : (pigeonVar_list[2] is Int64? ? pigeonVar_list[2] as! Int64? : Int64(pigeonVar_list[2] as! Int32))

    return CupertinoVideoOptions(
      fileType: fileType,
      codec: codec,
      fps: fps
    )
  }
  func toList() -> [Any?] {
    return [
      fileType,
      codec,
      fps,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonSensorTypeDevice {
  var sensorType: PigeonSensorType
  /// A localized device name for display in the user interface.
  var name: String
  /// The current exposure ISO value.
  var iso: Double
  /// A Boolean value that indicates whether the flash is currently available for use.
  var flashAvailable: Bool
  /// An identifier that uniquely identifies the device.
  var uid: String



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonSensorTypeDevice? {
    let sensorType = pigeonVar_list[0] as! PigeonSensorType
    let name = pigeonVar_list[1] as! String
    let iso = pigeonVar_list[2] as! Double
    let flashAvailable = pigeonVar_list[3] as! Bool
    let uid = pigeonVar_list[4] as! String

    return PigeonSensorTypeDevice(
      sensorType: sensorType,
      name: name,
      iso: iso,
      flashAvailable: flashAvailable,
      uid: uid
    )
  }
  func toList() -> [Any?] {
    return [
      sensorType,
      name,
      iso,
      flashAvailable,
      uid,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidFocusSettings {
  /// The auto focus will be canceled after the given [autoCancelDurationInMillis].
  /// If [autoCancelDurationInMillis] is equals to 0 (or less), the auto focus
  /// will **not** be canceled. A manual `focusOnPoint` call will be needed to
  /// focus on an other point.
  /// Minimal duration of [autoCancelDurationInMillis] is 1000 ms. If set
  /// between 0 (exclusive) and 1000 (exclusive), it will be raised to 1000.
  var autoCancelDurationInMillis: Int64



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidFocusSettings? {
    let autoCancelDurationInMillis = pigeonVar_list[0] is Int64 ? pigeonVar_list[0] as! Int64 : Int64(pigeonVar_list[0] as! Int32)

    return AndroidFocusSettings(
      autoCancelDurationInMillis: autoCancelDurationInMillis
    )
  }
  func toList() -> [Any?] {
    return [
      autoCancelDurationInMillis
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaneWrapper {
  var bytes: FlutterStandardTypedData
  var bytesPerRow: Int64
  var bytesPerPixel: Int64? = nil
  var width: Int64? = nil
  var height: Int64? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaneWrapper? {
    let bytes = pigeonVar_list[0] as! FlutterStandardTypedData
    let bytesPerRow = pigeonVar_list[1] is Int64 ? pigeonVar_list[1] as! Int64 : Int64(pigeonVar_list[1] as! Int32)
    let bytesPerPixel: Int64? = isNullish(pigeonVar_list[2]) ? nil : (pigeonVar_list[2] is Int64? ? pigeonVar_list[2] as! Int64? : Int64(pigeonVar_list[2] as! Int32))
    let width: Int64? = isNullish(pigeonVar_list[3]) ? nil : (pigeonVar_list[3] is Int64? ? pigeonVar_list[3] as! Int64? : Int64(pigeonVar_list[3] as! Int32))
    let height: Int64? = isNullish(pigeonVar_list[4]) ? nil : (pigeonVar_list[4] is Int64? ? pigeonVar_list[4] as! Int64? : Int64(pigeonVar_list[4] as! Int32))

    return PlaneWrapper(
      bytes: bytes,
      bytesPerRow: bytesPerRow,
      bytesPerPixel: bytesPerPixel,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      bytes,
      bytesPerRow,
      bytesPerPixel,
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CropRectWrapper {
  var left: Int64
  var top: Int64
  var width: Int64
  var height: Int64



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CropRectWrapper? {
    let left = pigeonVar_list[0] is Int64 ? pigeonVar_list[0] as! Int64 : Int64(pigeonVar_list[0] as! Int32)
    let top = pigeonVar_list[1] is Int64 ? pigeonVar_list[1] as! Int64 : Int64(pigeonVar_list[1] as! Int32)
    let width = pigeonVar_list[2] is Int64 ? pigeonVar_list[2] as! Int64 : Int64(pigeonVar_list[2] as! Int32)
    let height = pigeonVar_list[3] is Int64 ? pigeonVar_list[3] as! Int64 : Int64(pigeonVar_list[3] as! Int32)

    return CropRectWrapper(
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnalysisImageWrapper {
  var format: AnalysisImageFormat
  var bytes: FlutterStandardTypedData? = nil
  var width: Int64
  var height: Int64
  var planes: [PlaneWrapper?]? = nil
  var cropRect: CropRectWrapper? = nil
  var rotation: AnalysisRotation? = nil



  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalysisImageWrapper? {
    let format = pigeonVar_list[0] as! AnalysisImageFormat
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let width = pigeonVar_list[2] is Int64 ? pigeonVar_list[2] as! Int64 : Int64(pigeonVar_list[2] as! Int32)
    let height = pigeonVar_list[3] is Int64 ? pigeonVar_list[3] as! Int64 : Int64(pigeonVar_list[3] as! Int32)
    let planes: [PlaneWrapper?]? = nilOrValue(pigeonVar_list[4])
    let cropRect: CropRectWrapper? = nilOrValue(pigeonVar_list[5])
    let rotation: AnalysisRotation? = nilOrValue(pigeonVar_list[6])

    return AnalysisImageWrapper(
      format: format,
      bytes: bytes,
      width: width,
      height: height,
      planes: planes,
      cropRect: cropRect,
      rotation: rotation
    )
  }
  func toList() -> [Any?] {
    return [
      format,
      bytes,
      width,
      height,
      planes,
      cropRect,
      rotation,
    ]
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return PigeonSensorPosition(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return VideoRecordingQuality(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return QualityFallbackStrategy(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CupertinoFileType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CupertinoCodecType(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return PigeonSensorType(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return CamerAwesomePermission(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return AnalysisImageFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        return AnalysisRotation(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      return PreviewSize.fromList(self.readValue() as! [Any?])
    case 139:
      return ExifPreferences.fromList(self.readValue() as! [Any?])
    case 140:
      return PigeonSensor.fromList(self.readValue() as! [Any?])
    case 141:
      return VideoOptions.fromList(self.readValue() as! [Any?])
    case 142:
      return AndroidVideoOptions.fromList(self.readValue() as! [Any?])
    case 143:
      return CupertinoVideoOptions.fromList(self.readValue() as! [Any?])
    case 144:
      return PigeonSensorTypeDevice.fromList(self.readValue() as! [Any?])
    case 145:
      return AndroidFocusSettings.fromList(self.readValue() as! [Any?])
    case 146:
      return PlaneWrapper.fromList(self.readValue() as! [Any?])
    case 147:
      return CropRectWrapper.fromList(self.readValue() as! [Any?])
    case 148:
      return AnalysisImageWrapper.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonSensorPosition {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoRecordingQuality {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? QualityFallbackStrategy {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? CupertinoFileType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CupertinoCodecType {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PigeonSensorType {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? CamerAwesomePermission {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? AnalysisImageFormat {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? AnalysisRotation {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? PreviewSize {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ExifPreferences {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonSensor {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? VideoOptions {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidVideoOptions {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? CupertinoVideoOptions {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonSensorTypeDevice {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidFocusSettings {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? PlaneWrapper {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? CropRectWrapper {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? AnalysisImageWrapper {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AnalysisImageUtils {
  func nv21toJpeg(nv21Image: AnalysisImageWrapper, jpegQuality: Int64, completion: @escaping (Result<AnalysisImageWrapper, Error>) -> Void)
  func yuv420toJpeg(yuvImage: AnalysisImageWrapper, jpegQuality: Int64, completion: @escaping (Result<AnalysisImageWrapper, Error>) -> Void)
  func yuv420toNv21(yuvImage: AnalysisImageWrapper, completion: @escaping (Result<AnalysisImageWrapper, Error>) -> Void)
  func bgra8888toJpeg(bgra8888image: AnalysisImageWrapper, jpegQuality: Int64, completion: @escaping (Result<AnalysisImageWrapper, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AnalysisImageUtilsSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `AnalysisImageUtils` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AnalysisImageUtils?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let nv21toJpegChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.AnalysisImageUtils.nv21toJpeg\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      nv21toJpegChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nv21ImageArg = args[0] as! AnalysisImageWrapper
        let jpegQualityArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        api.nv21toJpeg(nv21Image: nv21ImageArg, jpegQuality: jpegQualityArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      nv21toJpegChannel.setMessageHandler(nil)
    }
    let yuv420toJpegChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.AnalysisImageUtils.yuv420toJpeg\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      yuv420toJpegChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let yuvImageArg = args[0] as! AnalysisImageWrapper
        let jpegQualityArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        api.yuv420toJpeg(yuvImage: yuvImageArg, jpegQuality: jpegQualityArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      yuv420toJpegChannel.setMessageHandler(nil)
    }
    let yuv420toNv21Channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.AnalysisImageUtils.yuv420toNv21\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      yuv420toNv21Channel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let yuvImageArg = args[0] as! AnalysisImageWrapper
        api.yuv420toNv21(yuvImage: yuvImageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      yuv420toNv21Channel.setMessageHandler(nil)
    }
    let bgra8888toJpegChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.AnalysisImageUtils.bgra8888toJpeg\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bgra8888toJpegChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bgra8888imageArg = args[0] as! AnalysisImageWrapper
        let jpegQualityArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        api.bgra8888toJpeg(bgra8888image: bgra8888imageArg, jpegQuality: jpegQualityArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      bgra8888toJpegChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraInterface {
  func setupCamera(sensors: [PigeonSensor], aspectRatio: String, zoom: Double, mirrorFrontCamera: Bool, enablePhysicalButton: Bool, flashMode: String, captureMode: String, enableImageStream: Bool, exifPreferences: ExifPreferences, videoOptions: VideoOptions?, completion: @escaping (Result<Bool, Error>) -> Void)
  func checkPermissions(permissions: [String]) throws -> [String]
  /// Returns given [CamerAwesomePermission] list (as String). Location permission might be
  /// refused but the app should still be able to run.
  func requestPermissions(saveGpsLocation: Bool, completion: @escaping (Result<[String], Error>) -> Void)
  func getPreviewTextureId(cameraPosition: Int64) throws -> Int64
  func takePhoto(sensors: [PigeonSensor], paths: [String?], completion: @escaping (Result<Bool, Error>) -> Void)
  func recordVideo(sensors: [PigeonSensor], paths: [String?], completion: @escaping (Result<Void, Error>) -> Void)
  func pauseVideoRecording() throws
  func resumeVideoRecording() throws
  func receivedImageFromStream() throws
  func setManualIso(iso: Double) throws
  func stopRecordingVideo(completion: @escaping (Result<Bool, Error>) -> Void)
  func getFrontSensors() throws -> [PigeonSensorTypeDevice]
  func getBackSensors() throws -> [PigeonSensorTypeDevice]
  func start() throws -> Bool
  func stop() throws -> Bool
  func setFlashMode(mode: String) throws
  func handleAutoFocus() throws
  /// Starts auto focus on a point at ([x], [y]).
  ///
  /// On Android, you can control after how much time you want to switch back
  /// to passive focus mode with [androidFocusSettings].
  func focusOnPoint(previewSize: PreviewSize, x: Double, y: Double, androidFocusSettings: AndroidFocusSettings?) throws
  func setZoom(zoom: Double) throws
  func setMirrorFrontCamera(mirror: Bool) throws
  func setSensor(sensors: [PigeonSensor]) throws
  func setCorrection(brightness: Double) throws
  func getMinZoom() throws -> Double
  func getMaxZoom() throws -> Double
  func setCaptureMode(mode: String) throws
  func setRecordingAudioMode(enableAudio: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func availableSizes() throws -> [PreviewSize]
  func refresh() throws
  func getEffectivPreviewSize(index: Int64) throws -> PreviewSize?
  func setPhotoSize(size: PreviewSize) throws
  func setPreviewSize(size: PreviewSize) throws
  func setAspectRatio(aspectRatio: String) throws
  func setupImageAnalysisStream(format: String, width: Int64, maxFramesPerSecond: Double?, autoStart: Bool) throws
  func setExifPreferences(exifPreferences: ExifPreferences, completion: @escaping (Result<Bool, Error>) -> Void)
  func startAnalysis() throws
  func stopAnalysis() throws
  func setFilter(matrix: [Double]) throws
  func isVideoRecordingAndImageAnalysisSupported(sensor: PigeonSensorPosition, completion: @escaping (Result<Bool, Error>) -> Void)
  func isMultiCamSupported() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraInterfaceSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `CameraInterface` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraInterface?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setupCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setupCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sensorsArg = args[0] as! [PigeonSensor]
        let aspectRatioArg = args[1] as! String
        let zoomArg = args[2] as! Double
        let mirrorFrontCameraArg = args[3] as! Bool
        let enablePhysicalButtonArg = args[4] as! Bool
        let flashModeArg = args[5] as! String
        let captureModeArg = args[6] as! String
        let enableImageStreamArg = args[7] as! Bool
        let exifPreferencesArg = args[8] as! ExifPreferences
        let videoOptionsArg: VideoOptions? = nilOrValue(args[9])
        api.setupCamera(sensors: sensorsArg, aspectRatio: aspectRatioArg, zoom: zoomArg, mirrorFrontCamera: mirrorFrontCameraArg, enablePhysicalButton: enablePhysicalButtonArg, flashMode: flashModeArg, captureMode: captureModeArg, enableImageStream: enableImageStreamArg, exifPreferences: exifPreferencesArg, videoOptions: videoOptionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setupCameraChannel.setMessageHandler(nil)
    }
    let checkPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.checkPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionsArg = args[0] as! [String]
        do {
          let result = try api.checkPermissions(permissions: permissionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkPermissionsChannel.setMessageHandler(nil)
    }
    /// Returns given [CamerAwesomePermission] list (as String). Location permission might be
    /// refused but the app should still be able to run.
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let saveGpsLocationArg = args[0] as! Bool
        api.requestPermissions(saveGpsLocation: saveGpsLocationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let getPreviewTextureIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.getPreviewTextureId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPreviewTextureIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraPositionArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          let result = try api.getPreviewTextureId(cameraPosition: cameraPositionArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPreviewTextureIdChannel.setMessageHandler(nil)
    }
    let takePhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.takePhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePhotoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sensorsArg = args[0] as! [PigeonSensor]
        let pathsArg = args[1] as! [String?]
        api.takePhoto(sensors: sensorsArg, paths: pathsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takePhotoChannel.setMessageHandler(nil)
    }
    let recordVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.recordVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recordVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sensorsArg = args[0] as! [PigeonSensor]
        let pathsArg = args[1] as! [String?]
        api.recordVideo(sensors: sensorsArg, paths: pathsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recordVideoChannel.setMessageHandler(nil)
    }
    let pauseVideoRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.pauseVideoRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseVideoRecordingChannel.setMessageHandler { _, reply in
        do {
          try api.pauseVideoRecording()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseVideoRecordingChannel.setMessageHandler(nil)
    }
    let resumeVideoRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.resumeVideoRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeVideoRecordingChannel.setMessageHandler { _, reply in
        do {
          try api.resumeVideoRecording()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeVideoRecordingChannel.setMessageHandler(nil)
    }
    let receivedImageFromStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.receivedImageFromStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      receivedImageFromStreamChannel.setMessageHandler { _, reply in
        do {
          try api.receivedImageFromStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      receivedImageFromStreamChannel.setMessageHandler(nil)
    }
    let setManualIsoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setManualIso\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setManualIsoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isoArg = args[0] as! Double
        do {
          try api.setManualIso(iso: isoArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setManualIsoChannel.setMessageHandler(nil)
    }
    let stopRecordingVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.stopRecordingVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingVideoChannel.setMessageHandler { _, reply in
        api.stopRecordingVideo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopRecordingVideoChannel.setMessageHandler(nil)
    }
    let getFrontSensorsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.getFrontSensors\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFrontSensorsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFrontSensors()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFrontSensorsChannel.setMessageHandler(nil)
    }
    let getBackSensorsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.getBackSensors\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBackSensorsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBackSensors()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBackSensorsChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        do {
          let result = try api.start()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          let result = try api.stop()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let setFlashModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setFlashMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFlashModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! String
        do {
          try api.setFlashMode(mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFlashModeChannel.setMessageHandler(nil)
    }
    let handleAutoFocusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.handleAutoFocus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleAutoFocusChannel.setMessageHandler { _, reply in
        do {
          try api.handleAutoFocus()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handleAutoFocusChannel.setMessageHandler(nil)
    }
    /// Starts auto focus on a point at ([x], [y]).
    ///
    /// On Android, you can control after how much time you want to switch back
    /// to passive focus mode with [androidFocusSettings].
    let focusOnPointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.focusOnPoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      focusOnPointChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let previewSizeArg = args[0] as! PreviewSize
        let xArg = args[1] as! Double
        let yArg = args[2] as! Double
        let androidFocusSettingsArg: AndroidFocusSettings? = nilOrValue(args[3])
        do {
          try api.focusOnPoint(previewSize: previewSizeArg, x: xArg, y: yArg, androidFocusSettings: androidFocusSettingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      focusOnPointChannel.setMessageHandler(nil)
    }
    let setZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZoomChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let zoomArg = args[0] as! Double
        do {
          try api.setZoom(zoom: zoomArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setZoomChannel.setMessageHandler(nil)
    }
    let setMirrorFrontCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setMirrorFrontCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMirrorFrontCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mirrorArg = args[0] as! Bool
        do {
          try api.setMirrorFrontCamera(mirror: mirrorArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMirrorFrontCameraChannel.setMessageHandler(nil)
    }
    let setSensorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setSensor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSensorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sensorsArg = args[0] as! [PigeonSensor]
        do {
          try api.setSensor(sensors: sensorsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSensorChannel.setMessageHandler(nil)
    }
    let setCorrectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setCorrection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCorrectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let brightnessArg = args[0] as! Double
        do {
          try api.setCorrection(brightness: brightnessArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCorrectionChannel.setMessageHandler(nil)
    }
    let getMinZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.getMinZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMinZoomChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMinZoom()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMinZoomChannel.setMessageHandler(nil)
    }
    let getMaxZoomChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.getMaxZoom\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMaxZoomChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMaxZoom()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMaxZoomChannel.setMessageHandler(nil)
    }
    let setCaptureModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setCaptureMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCaptureModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! String
        do {
          try api.setCaptureMode(mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCaptureModeChannel.setMessageHandler(nil)
    }
    let setRecordingAudioModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setRecordingAudioMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRecordingAudioModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enableAudioArg = args[0] as! Bool
        api.setRecordingAudioMode(enableAudio: enableAudioArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setRecordingAudioModeChannel.setMessageHandler(nil)
    }
    let availableSizesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.availableSizes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      availableSizesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.availableSizes()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      availableSizesChannel.setMessageHandler(nil)
    }
    let refreshChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.refresh\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshChannel.setMessageHandler { _, reply in
        do {
          try api.refresh()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      refreshChannel.setMessageHandler(nil)
    }
    let getEffectivPreviewSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.getEffectivPreviewSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEffectivPreviewSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          let result = try api.getEffectivPreviewSize(index: indexArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getEffectivPreviewSizeChannel.setMessageHandler(nil)
    }
    let setPhotoSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setPhotoSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPhotoSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sizeArg = args[0] as! PreviewSize
        do {
          try api.setPhotoSize(size: sizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPhotoSizeChannel.setMessageHandler(nil)
    }
    let setPreviewSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setPreviewSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPreviewSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sizeArg = args[0] as! PreviewSize
        do {
          try api.setPreviewSize(size: sizeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPreviewSizeChannel.setMessageHandler(nil)
    }
    let setAspectRatioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setAspectRatio\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAspectRatioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aspectRatioArg = args[0] as! String
        do {
          try api.setAspectRatio(aspectRatio: aspectRatioArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAspectRatioChannel.setMessageHandler(nil)
    }
    let setupImageAnalysisStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setupImageAnalysisStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupImageAnalysisStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let formatArg = args[0] as! String
        let widthArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        let maxFramesPerSecondArg: Double? = nilOrValue(args[2])
        let autoStartArg = args[3] as! Bool
        do {
          try api.setupImageAnalysisStream(format: formatArg, width: widthArg, maxFramesPerSecond: maxFramesPerSecondArg, autoStart: autoStartArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setupImageAnalysisStreamChannel.setMessageHandler(nil)
    }
    let setExifPreferencesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setExifPreferences\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExifPreferencesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let exifPreferencesArg = args[0] as! ExifPreferences
        api.setExifPreferences(exifPreferences: exifPreferencesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setExifPreferencesChannel.setMessageHandler(nil)
    }
    let startAnalysisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.startAnalysis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAnalysisChannel.setMessageHandler { _, reply in
        do {
          try api.startAnalysis()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAnalysisChannel.setMessageHandler(nil)
    }
    let stopAnalysisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.stopAnalysis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAnalysisChannel.setMessageHandler { _, reply in
        do {
          try api.stopAnalysis()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopAnalysisChannel.setMessageHandler(nil)
    }
    let setFilterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.setFilter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFilterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let matrixArg = args[0] as! [Double]
        do {
          try api.setFilter(matrix: matrixArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFilterChannel.setMessageHandler(nil)
    }
    let isVideoRecordingAndImageAnalysisSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.isVideoRecordingAndImageAnalysisSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isVideoRecordingAndImageAnalysisSupportedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sensorArg = args[0] as! PigeonSensorPosition
        api.isVideoRecordingAndImageAnalysisSupported(sensor: sensorArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isVideoRecordingAndImageAnalysisSupportedChannel.setMessageHandler(nil)
    }
    let isMultiCamSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camerawesome.CameraInterface.isMultiCamSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isMultiCamSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isMultiCamSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isMultiCamSupportedChannel.setMessageHandler(nil)
    }
  }
}
